# Generated by Django 5.2.1 on 2026-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_customer_alter_booking_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='spareparts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
