# Generated by Django 5.2.1 on 2026-01-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
