# Generated by Django 5.2.1 on 2026-01-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contactmessage_delete_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
